/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColegioRouteImport } from './routes/colegio'
import { Route as FinanzasRouteImport } from './routes/finanzas'
import { Route as HogarRouteImport } from './routes/hogar'
import { Route as VehiculosRouteImport } from './routes/vehiculos'
import { Route as ViajesRouteImport } from './routes/viajes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColegioRoute = ColegioRouteImport.update({
  id: '/colegio',
  path: '/colegio',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzasRoute = FinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => rootRouteImport,
} as any)
const HogarRoute = HogarRouteImport.update({
  id: '/hogar',
  path: '/hogar',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculosRoute = VehiculosRouteImport.update({
  id: '/vehiculos',
  path: '/vehiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const ViajesRoute = ViajesRouteImport.update({
  id: '/viajes',
  path: '/viajes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colegio': typeof ColegioRoute
  '/finanzas': typeof FinanzasRoute
  '/hogar': typeof HogarRoute
  '/vehiculos': typeof VehiculosRoute
  '/viajes': typeof ViajesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colegio': typeof ColegioRoute
  '/finanzas': typeof FinanzasRoute
  '/hogar': typeof HogarRoute
  '/vehiculos': typeof VehiculosRoute
  '/viajes': typeof ViajesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colegio': typeof ColegioRoute
  '/finanzas': typeof FinanzasRoute
  '/hogar': typeof HogarRoute
  '/vehiculos': typeof VehiculosRoute
  '/viajes': typeof ViajesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/colegio' | '/finanzas' | '/hogar' | '/vehiculos' | '/viajes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/colegio' | '/finanzas' | '/hogar' | '/vehiculos' | '/viajes'
  id:
    | '__root__'
    | '/'
    | '/colegio'
    | '/finanzas'
    | '/hogar'
    | '/vehiculos'
    | '/viajes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColegioRoute: typeof ColegioRoute
  FinanzasRoute: typeof FinanzasRoute
  HogarRoute: typeof HogarRoute
  VehiculosRoute: typeof VehiculosRoute
  ViajesRoute: typeof ViajesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colegio': {
      id: '/colegio'
      path: '/colegio'
      fullPath: '/colegio'
      preLoaderRoute: typeof ColegioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanzas': {
      id: '/finanzas'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof FinanzasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hogar': {
      id: '/hogar'
      path: '/hogar'
      fullPath: '/hogar'
      preLoaderRoute: typeof HogarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehiculos': {
      id: '/vehiculos'
      path: '/vehiculos'
      fullPath: '/vehiculos'
      preLoaderRoute: typeof VehiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viajes': {
      id: '/viajes'
      path: '/viajes'
      fullPath: '/viajes'
      preLoaderRoute: typeof ViajesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColegioRoute: ColegioRoute,
  FinanzasRoute: FinanzasRoute,
  HogarRoute: HogarRoute,
  VehiculosRoute: VehiculosRoute,
  ViajesRoute: ViajesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
